# The [import] section defines how to import data from source files.
# Read more in the README about source data file formats.

[import]
# src: a list of glob patterns defining which files to import.
# The search is relative to the directory containing the configuration file.
# The pattern '**' means to recurse into zero or more nested directories.
#
# Read about globs here:  https://en.wikipedia.org/wiki/Glob_(programming)
#
# Files found by more than one glob pattern (such as the file under 2021/09/30
# which in the example below will be found three times) will only be imported once.
src = [
    "indata/2021/**/*.dat",
    "indata/2021/09/30/*.dat",
    "indata/2021/09/30/JFAADS2179-20210930-022526-DataLog_User.dat",
]

# timestamp_col: The column in the source data files that defines the
# timestamp of each sample.
# Read more in the README section on timestamps.
timestamp_col = "EPOCH_TIME"

# sep: The separator used in source data files. This is optional.
# The default is sep = '\s+' which means one or more whitespace characters.
# For csv files, use, e.g., sep = ","
# sep = "," # for csv file

# The [import.columns] section specifies the columns to import from source
# files, and what data types to store them as.
# Read more about data types in the README.

[import.columns]
EPOCH_TIME = "float64" # floating-point Unix timestamp indata must be float64
# In our Picarro data files, solenoid_valves is a number specifying the current
# closed chamber.
# Normally, the numbers are integers, but specified with many zero decimals.
# When the machine is switching from one chamber to the next, the number sometimes
# is a non-integer number for 1-2 seconds. (See the example data files.)
# For this reason, we read solenoid_valves as float16 type.
solenoid_valves = "float16"
ALARM_STATUS = "uint8" # uint8: integers 0-255
CO2 = "float32" # float32 gives more than sufficient precision for gas concentrations
N2O_dry = "float32"
CH4_dry = "float32"
