repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files: \.py$

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
